### ISSUE TITLE
Remove TaggablePoolTrait from AbstractCachePool

### ISSUE THREAD

**Issue by boekkooi** [php-cache/adapter-common#15]
I propose to remove the `TaggablePoolTrait` form `AbstractCachePool` for the following reasons:
- The way that tag's should be implememented depends a lot on the cache backend.
   For example: within MongoDB you can add a tags property so manage tags but within the filesystem you need to maintain a second cache or some other index.
- The current Trait is not cleanup after it self (see for example [flushTag](https://github.com/php-cache/taggable-cache/blob/master/src/TaggablePoolTrait.php#L70)).
   This makes (for example) the filesystem-adapter keep cache file even when the tags are cleared.

What do you guys/girls think?

**Comment by Nyholm** [comment]
I agree with you that on some adapters this could be improved for performance. The purpose of the taggable trait, hierarchy trait and the AbstractCachePool it so make it quick and easy to implement new pools. The pools it self should later be updated to be more performant and eventually not use the traits at all. 
Example: an easy fix would be for the RedisCachePool to implement hasItem() instead of using the AbstractCachePool. Because it would be more performant.

**Comment by aequasi** [comment]
@boekkooi Can you please open this issue on https://github.com/php-cache/issues/issues, thanks :)
